const computerChoice = document.getElementById('computer-choice')
const userChoice = document.getElementById('user-choice')
const result = document.getElementById('result')
const rock = document.getElementById('rock')
const paper = document.getElementById('paper')
const scissors = document.getElementById('scissors')